Update certinfo.go
smallstep/certinfo pull request #10
Opened 2021-07-08 23:56 UTC by tommy-56

Addressing Issue 446 in CLI (https://github.com/smallstep/cli/issues/446). Email name constraint missing. This displays the missing email name constraint mentioned in the issue.

2021-07-09 00:21 UTC, dopey commented
https://github.com/smallstep/cli/issues/446#issuecomment-876824658

2021-07-09 21:02 UTC, tommy-56 commented
Example Output of step certificate inspect with changes to certInfo.go
Certificate:
    Additional Cert info Here ...
            X509v3 Name Constraints:
                Permitted:
                  DNS: Pexample.com
                  Email: jane@doe.com
                  URI: https://doe.com
                  IP Range: 1.2.3.0/24
                Excluded:
                  DNS: ExcludexampleDNS.net
                  Email: janeexcluded@doe.org
                  URI: https://EXdoe.org
                  IP Range: 3.2.1.0/24
    Signature Algorithm: ECDSA-SHA256
         30:46:02:21:00:f2:c9:87:6d:97:dc:25:06:1e:30:38:ab:ab:
         10:73:09:26:16:50:2f:57:65:b3:14:94:79:f3:04:d3:8e:68:
         c3:02:21:00:c9:59:6c:89:77:a2:46:69:45:7a:28:1a:c0:37:
         8a:aa:e1:78:d2:74:bc:78:50:a1:a6:89:84:19:5b:96:a1:b4
		 
------------
Multiple Constraints
Certificate:
    Additional Cert info Here... 
            X509v3 Name Constraints:
                Permitted:
                  DNS: Pexample.com, PermitMe.org, permitMe2.net
                  Email: jane@doe.com, permit@smallstep.com
                  URI: https://doe.com, https://jonPermitURI.com
                  IP Range: 1.2.3.0/24, 5.6.7.0/24
                Excluded:
                  DNS: ExcludexampleDNS.net, ExcludeMe.org
                  Email: janeExcluded@doe.org, johnExclude@smallstep.com
                  URI: https://EXdoe.org, EXJon.net
                  IP Range: 3.2.1.0/24, 1.2.3.0/24
    Signature Algorithm: ECDSA-SHA256
         30:45:02:20:50:ac:60:bb:d9:46:13:ed:23:1f:fd:d4:1d:ee:
         8f:90:ca:53:0a:50:8e:91:20:2c:3e:f4:f3:ca:78:2a:40:8d:
         02:21:00:e2:ce:34:29:20:5a:85:c1:40:e1:10:3f:0e:e1:d7:
         97:fb:40:24:43:32:0c:c4:cd:4d:ae:72:94:3f:f3:b5:fd

2021-08-03 20:16 UTC, dopey commented on certinfo.go
> +						buf.WriteString(fmt.Sprintf("%16sPermitted:\n%18sDNS: %s", "", "", cert.PermittedDNSDomains[0]))
Seems like `Permitted` will only be printed if dnsdomains is not empty. Doesn't take into account that dnsDomains might be empty while other stuff is not. Same is true for `Excluded` below.

2021-08-03 20:17 UTC, dopey requested changes
see comment in code.

2021-08-09 19:08 UTC, dopey approved these changes
lgtm

2021-08-09 19:09 UTC, merged