Update golang in go.mod and linter updates
smallstep/certinfo pull request #38
Opened 2023-09-11 21:18 UTC by dopey

2023-09-19 22:05 UTC, hslatman submitted a review, later dismissed

2023-09-20 21:48 UTC, maraino requested changes

2023-09-20 21:48 UTC, maraino commented on certformat_test.go
> +	if block == nil || len(rest) > 0 || block.Bytes == nil {
The last condition is not really possible, but `len(block.Bytes) == 0` is, the following per file will return that:
```
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
```

2023-09-20 21:48 UTC, maraino commented on certformat_test.go
> +	if block == nil || len(rest) > 0 || block.Bytes == nil {
ditto

2023-10-09 13:41 UTC, hslatman commented
@dopey this is soft blocking other (automatic) PRs, so would be great if you could have another look 🙂

2023-10-09 17:05 UTC, hslatman approved these changes

2023-10-09 17:08 UTC, maraino approved these changes

2023-10-09 17:08 UTC, merged